source 'https://github.com/adxcorp/AdxLibrary_iOS_Release.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'ADXSampleSwift' do
  use_frameworks!

  # 라이브러리 전체를 포함할 경우 
  pod 'ADXLibrary', '2.5.0'

  # 네이티브만 포함할 경우
  # pod 'ADXLibrary/Native', '2.5.0'

  # 전면/배너만 포함할 경우
  # pod 'ADXLibrary/Standard', '2.5.0'

  # 리워드만 포함할 경우 
  # pod 'ADXLibrary/Rewarded', '2.5.0'

end
