source 'https://github.com/adxcorp/AdxLibrary_iOS_Release.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ADXSampleSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ADXSampleSwiftUI

  # 라이브러리 전체를 포함할 경우 
  pod 'ADXLibrary', '2.5.1'

  # 네이티브만 포함할 경우
  # pod 'ADXLibrary/Native', '2.5.1'

  # 전면/배너만 포함할 경우
  # pod 'ADXLibrary/Standard', '2.5.1'

  # 리워드만 포함할 경우 
  # pod 'ADXLibrary/Rewarded', '2.5.1'

end
